cabal-version:      2.4
name:               netwire01-web
version:            0.1.0.0
synopsis:           Web (GHC JavaScript backend) frontend for netwire01
build-type:         Simple

executable netwire01-web
  main-is:          Main.hs
  hs-source-dirs:   .
  build-depends:    base
                  , netwire
  default-language: Haskell2010
  ghc-options:      -O2
